# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18nOhAHVE8OkQHzE_7nrUlzAuW7kxTbK3
"""

!pip install kaggle

!mkdir ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d arbethi/diabetic-retinopathy-level-detection

!unzip diabetic-retinopathy-level-detection.zip

imageSize= [299,299]

trainpath=r"/content/preprocessed dataset/preprocessed dataset/training"
testpath=r"/content/preprocessed dataset/preprocessed dataset/testing"

from tensorflow.keras.layers import Dense,Flatten,Input
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img
from tensorflow.keras.applications.xception import Xception,preprocess_input
from glob import glob
import numpy as np
import matplotlib.pyplot as plt

train_datagen=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
test_datagen=ImageDataGenerator(rescale=1./255)

training_set=train_datagen.flow_from_directory("/content/preprocessed dataset/preprocessed dataset/training",target_size=(299,299),batch_size=32,class_mode='categorical')
test_set=test_datagen.flow_from_directory("/content/preprocessed dataset/preprocessed dataset/testing",target_size=(299,299),batch_size=32,class_mode='categorical')

